name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - uses: aarnott/nbgv@v0.4.0
      with:
        setAllVars: true
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
     
    - name: dotnet build
      run: dotnet build FeatherHttp.sln -c Release    

    # update the FeatherHttpContent to have the latest prerelease version of FeatherHttp
    - name: update template nuget package
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: | 
        ((Get-Content -path ./src/FeatherHttp.Templates/Content/FeatherHttp-Template.csproj -Raw) -replace "\$\(PackageVersion\)", $env:NBGV_NuGetPackageVersion) | Set-Content -Path ./src/FeatherHttp.Templates/Content/FeatherHttp-Template.csproj

    - name: dotnet test
      run: dotnet test FeatherHttp.sln -c Release --no-build

    - name: dotnet pack
      run: dotnet pack FeatherHttp.sln -c Release --no-build --include-source --include-symbols

    - name: setup nuget
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: latest

    - name: Set API key
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: nuget setapikey ${{ secrets.FEEDZ_TOKEN }} -Config nuget.config -Source https://f.feedz.io/featherhttp/framework/nuget/index.json

    - name: Set symbols API key
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: nuget setapikey ${{ secrets.FEEDZ_TOKEN }} -Config nuget.config -Source https://f.feedz.io/featherhttp/framework/symbols

    - name: push packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet nuget push **/*.nupkg -s https://f.feedz.io/featherhttp/framework/nuget/index.json -ss https://f.feedz.io/featherhttp/framework/symbols --skip-duplicate
